#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
BASELINE  --  Fractal image coding of medical (MRI) images following
    S. Bhavani, K. Thanushkodi, "Neural based domain and range pool partitioning
    using Fractal Coding for nearly lossless Medical Image Compression",
    WSEAS Trans. on Signal Processing, 9(1), 2013.

This file is meant to be the REFERENCE for every later development:
no chaotic maps, no speed-ups, no extra metrics.  Only what the paper describes.

Algorithms (Section 3 of the paper)
  standard : fixed range blocks, all domain blocks, 8 isometries, full search.
  alg1     : quad-tree decomposition + variance based domain/range separation
             (threshold tau).  Domain blocks are kept LOSSLESSLY (seeds); the
             other blocks are generated by the IFS (fractal) code.
  alg2     : alg1 + Self-Organising-Map grouping.  A range block is matched only
             with the domain blocks of its own SOM group.

Data
  Reads the images straight from the ZIP archive (or from a folder), keeps ONE
  class (default: notumor) and N images (default: 5), converts them to 8-bit
  grey level and 512 x 512 (paper size).

Outputs (same layout as the paper)
  Table 1  PSNR at different thresholds          Fig. 1  partition + domain blocks (images 1, 2)
  Table 2  encoding time at different thresholds Fig. 2  domain blocks for several tau (images 3, 4)
  Table 3  compression ratio                     Fig. 3  performance analysis
  Table 4  the three algorithms, Sample image 4  Fig. 5-8 reconstruction + comparison charts

Run
  python fractal_baseline.py --source /content/drive/MyDrive/archive.zip
"""
import argparse
import glob
import io
import math
import os
import random
import time
import zipfile

import numpy as np

# ==========================================================================
# 1. FIXED PARAMETERS  (everything the paper does not specify is fixed HERE,
#    once, and written into the result file)
# ==========================================================================
IMG_SIZE = 512                 # paper: 512 x 512
TAU_LIST = [1e-3, 1e-4, 1e-5, 1e-6]   # paper: thresholds of Tables 1-3
DMIN = 8                       # minimum domain block size (d_min)
MAX_SIZE = 32                  # largest quad-tree block
RMIN = 4                       # smallest range block
SPLIT_VAR = 60.0               # quad-tree: a block is split while variance > SPLIT_VAR
TOL = 5.0                      # a range block is split when the RMS error of its best match > TOL
S_LEVELS = np.linspace(-0.95, 0.95, 31)   # quantised contrast s_i (|s| < 1: contractive)
S_BITS, O_BITS, ISO_BITS = 5, 9, 3        # bits of s_i, o_i, isometry
SOM_GRID = (3, 3)              # 9 groups
SOM_EPOCHS = 15
SOM_LR0 = 0.5
SOM_SEED = 0
STD_RANGE, STD_STRIDE = 8, 8   # standard coder: 8x8 ranges, 16x16 domains every 8 pixels
DECODE_ITERS = 12              # IFS iterations at decoding (paper: 4-8 are enough)
RULE = "figure"                # tau -> variance threshold, see separate_domain_range()
EXTS = (".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff")


# ==========================================================================
# 2. Utilities
# ==========================================================================
def psnr(a, b):
    mse = np.mean((a.astype(np.float64) - b.astype(np.float64)) ** 2)
    return 99.0 if mse == 0 else 10 * math.log10(255.0 ** 2 / mse)


def isometry(blocks, k):
    """One of the 8 isometries of a square (4 rotations x optional flip)."""
    if k >= 4:
        blocks = blocks[..., :, ::-1]
    return np.rot90(blocks, k % 4, axes=(-2, -1))


def pool2(img):
    """P[y, x] = mean of img[y:y+2, x:x+2]  (down-sampling of 2r x 2r domains to r x r)."""
    return 0.25 * (img[:-1, :-1] + img[1:, :-1] + img[:-1, 1:] + img[1:, 1:])


# ==========================================================================
# 3. Data: one class, N images, straight from the ZIP archive
# ==========================================================================
def list_images(source):
    """Return [(member_name, opener)] for every image of a .zip file or of a folder."""
    out = []
    if os.path.isfile(source) and source.lower().endswith(".zip"):
        z = zipfile.ZipFile(source)
        for n in sorted(z.namelist()):
            if n.lower().endswith(EXTS) and not n.endswith("/") and "__MACOSX" not in n:
                out.append((n, (lambda name=n: z.read(name))))
    elif os.path.isdir(source):
        for p in sorted(glob.glob(os.path.join(source, "**", "*"), recursive=True)):
            if p.lower().endswith(EXTS):
                rel = os.path.relpath(p, source).replace(os.sep, "/")
                out.append((rel, (lambda path=p: open(path, "rb").read())))
    else:
        raise SystemExit("--source must be a .zip file or a folder: %s" % source)
    return out


def select_images(source, cls, n, split, seed, manifest):
    """Choose n images of class `cls`.  The choice is deterministic and is written to
    `manifest`; if the manifest already exists it is re-used (same images in every run)."""
    items = dict(list_images(source))
    if manifest and os.path.exists(manifest):
        names = [l.strip() for l in open(manifest, encoding="utf-8") if l.strip()]
        missing = [m for m in names if m not in items]
        if missing:
            raise SystemExit("images of the manifest are not in the source: %s" % missing[:3])
        return names, items
    cand = [m for m in items if os.path.basename(os.path.dirname(m)).lower() == cls.lower()]
    if split:
        sp = [m for m in cand if ("/" + split.lower() + "/") in ("/" + m.lower())]
        cand = sp or cand
    if len(cand) < n:
        raise SystemExit("only %d images of class '%s' found (need %d)" % (len(cand), cls, n))
    names = sorted(random.Random(seed).sample(sorted(cand), n))
    return names, items


def load_image(data, size=IMG_SIZE):
    """bytes -> 8-bit grey level, size x size (bicubic resize when needed)."""
    from PIL import Image
    im = Image.open(io.BytesIO(data)).convert("L")
    if im.size != (size, size):
        im = im.resize((size, size), Image.BICUBIC)
    return np.asarray(im, dtype=np.float64)


# ==========================================================================
# 4. Quad-tree decomposition and domain / range separation (Section 3.1)
# ==========================================================================
def quadtree(img, max_size, min_size, split_var):
    """Variance driven quad-tree.  Returns the leaves (y, x, size)."""
    leaves = []

    def rec(y, x, s):
        blk = img[y:y + s, x:x + s]
        if s > min_size and (s > max_size or blk.var() > split_var):
            h = s // 2
            for dy in (0, h):
                for dx in (0, h):
                    rec(y + dy, x + dx, h)
        else:
            leaves.append((y, x, s))

    n = img.shape[0]
    for y in range(0, n, max_size):
        for x in range(0, n, max_size):
            rec(y, x, max_size)
    return leaves


def tau_effective(tau, rule=RULE):
    """
    The paper's separation rule (page 13):
        size(b) > d_min                          -> Range
        elif  var(b) >= tau * var_max            -> Domain  (feature rich)
        else                                     -> Range
    with var_max = maximum variance of the d_min x d_min blocks.

    rule = "literal": use tau exactly as printed.  With tau = 1e-3 ... 1e-6 almost
        EVERY d_min block becomes a domain block and tau has almost no effect.
    rule = "figure" (default): the paper's Fig. 2 shows the opposite behaviour
        (tau = 1e-3 keeps MORE domain blocks than tau = 1e-6).  To reproduce Fig. 2
        the ratio var/var_max is compared with
            tau_eff = 0.2 * (tau / 1e-6) ** (-1/3)
        i.e. 1e-3 -> 0.02, 1e-4 -> 0.043, 1e-5 -> 0.093, 1e-6 -> 0.2.
        (This mapping is OUR choice; the paper gives no formula.)
    """
    return tau if rule == "literal" else 0.2 * (tau / 1e-6) ** (-1.0 / 3.0)


def separate_domain_range(img, leaves, dmin, tau, rule=RULE):
    vmax = max(1e-9, max(img[y:y + s, x:x + s].var() for (y, x, s) in leaves if s == dmin))
    t_eff = tau_effective(tau, rule)
    dom, rng_ = [], []
    for (y, x, s) in leaves:
        if s == dmin and img[y:y + s, x:x + s].var() >= t_eff * vmax:
            dom.append((y, x, s))
        else:
            rng_.append((y, x, s))
    return dom, rng_, t_eff


# ==========================================================================
# 5. Self-Organising Map (Kohonen), Section 3.2
# ==========================================================================
class SOM:
    """
    1. randomise the weight vectors of the nodes   2. grab an input vector
    3. traverse every node   4. Euclidean distance between input and node weights
    5. the node with the smallest distance is the Best Matching Unit (BMU)
    6. update the neighbourhood of the BMU:
           Wv(t+1) = Wv(t) + theta(t) * alpha(t) * (D(t) - Wv(t))
    There is no activation function in a SOM: the winner is chosen by distance and
    theta(t) = exp(-d^2 / (2 sigma(t)^2)) is the (Gaussian) neighbourhood function.
    alpha(t) and sigma(t) decrease linearly.
    """

    def __init__(self, grid=SOM_GRID, epochs=SOM_EPOCHS, lr0=SOM_LR0, seed=SOM_SEED):
        self.grid, self.epochs, self.lr0 = grid, epochs, lr0
        self.rs = np.random.RandomState(seed)
        gy, gx = np.mgrid[0:grid[0], 0:grid[1]]
        self.pos = np.stack([gy.ravel(), gx.ravel()], 1).astype(float)
        self.n = grid[0] * grid[1]

    def fit(self, X):
        X = np.asarray(X, dtype=np.float64)
        idx = self.rs.choice(len(X), self.n, replace=len(X) < self.n)      # random initial weights
        self.W = X[idx].copy() + 1e-3 * self.rs.randn(self.n, X.shape[1])  # (= random training samples)
        total = self.epochs * len(X)
        t = 0
        sig0 = max(self.grid) / 2.0
        for _ in range(self.epochs):
            for i in self.rs.permutation(len(X)):
                f = 1.0 - t / total
                alpha, sig = self.lr0 * f, max(0.5, sig0 * f)
                d = ((self.W - X[i]) ** 2).sum(1)
                bmu = d.argmin()
                theta = np.exp(-((self.pos - self.pos[bmu]) ** 2).sum(1) / (2 * sig ** 2))
                self.W += (theta * alpha)[:, None] * (X[i] - self.W)
                t += 1
        return self

    def predict(self, X):
        X = np.asarray(X, dtype=np.float64)
        return ((X[:, None, :] - self.W[None]) ** 2).sum(2).argmin(1)


def block_features(blocks):
    """Feature vector of (N, r, r) blocks, invariant to the 8 isometries:
    mean, standard deviation and the sorted, normalised quadrant means."""
    n, r, _ = blocks.shape
    h = r // 2
    q = np.stack([blocks[:, :h, :h].mean((1, 2)), blocks[:, :h, h:].mean((1, 2)),
                  blocks[:, h:, :h].mean((1, 2)), blocks[:, h:, h:].mean((1, 2))], 1)
    mu = blocks.mean((1, 2))
    sd = blocks.std((1, 2))
    dev = np.sort(q - mu[:, None], 1) / (sd[:, None] + 1.0)
    return np.column_stack([mu / 255.0, np.minimum(sd, 64) / 64.0, 0.3 * dev])


# ==========================================================================
# 6. Fractal matching machinery (Section 2)
# ==========================================================================
class DomainPool:
    """Domain candidates for ONE range size r: windows 2r x 2r anchored at the domain
    (seed) blocks, down-sampled to r x r, each with its 8 isometries."""

    def __init__(self, P, anchors, r, n_img, use_som=False):
        pos = sorted({(min(y, n_img - 2 * r), min(x, n_img - 2 * r)) for (y, x) in anchors})
        self.pos = np.array(pos)
        base = np.stack([P[y:y + 2 * r:2, x:x + 2 * r:2] for (y, x) in pos])
        self.n, self.r = len(pos), r
        self.all = np.stack([isometry(base, k).reshape(self.n, -1)
                             for k in range(8)]).astype(np.float32)        # (8, N, r*r)
        self.sum_d = self.all[0].sum(1)
        self.sum_dd = (self.all[0] ** 2).sum(1)
        self.labels = None
        if use_som:
            self.som = SOM().fit(block_features(base))
            self.labels = self.som.predict(block_features(base))

    def candidates(self, label=None):
        """Indices of the domain windows that must be searched."""
        if label is None or self.labels is None:
            return np.arange(self.n)
        idx = np.where(self.labels == label)[0]
        if len(idx) == 0:                                    # empty group -> nearest non-empty one
            used = np.unique(self.labels)
            d = ((self.som.W[used] - self.som.W[label]) ** 2).sum(1)
            idx = np.where(self.labels == used[d.argmin()])[0]
        return idx


def best_match(rv, pool, idx):
    """Least-squares (s, o) for every candidate and isometry; returns the best
    (domain index, isometry, s index, o, squared error) for the range vector rv."""
    n = rv.size
    sr, srr = rv.sum(), (rv ** 2).sum()
    D = pool.all[:, idx, :]
    sd, sdd = pool.sum_d[idx], pool.sum_dd[idx]
    sdr = D @ rv.astype(np.float32)
    den = n * sdd - sd ** 2
    s = np.where(den > 1e-6, (n * sdr - sd * sr) / np.maximum(den, 1e-6), 0.0)
    si = np.abs(s[..., None] - S_LEVELS).argmin(-1)                     # quantise s
    sq = S_LEVELS[si]
    o = np.clip(np.rint((sr - sq * sd) / n), -256, 255)                 # quantise o
    sse = (sq ** 2 * sdd + n * o ** 2 + srr + 2 * sq * o * sd - 2 * sq * sdr - 2 * o * sr)
    k, m = np.unravel_index(sse.argmin(), sse.shape)
    return int(idx[m]), int(k), int(si[k, m]), int(o[k, m]), float(max(sse[k, m], 0))


# ==========================================================================
# 7. Encoder / decoder
# ==========================================================================
class Encoded:
    pass


def encode(img, algo, tau=1e-5, rule=RULE):
    """algo in {'standard', 'alg1', 'alg2'}"""
    t0 = time.perf_counter()
    n_img = img.shape[0]
    P = pool2(img)
    e = Encoded()
    e.algo, e.shape, e.maps, e.rmin = algo, img.shape, [], RMIN

    if algo == "standard":                                   # ---- standard fractal coding
        e.seed_mask = np.zeros(img.shape, bool)
        anchors = [(y, x) for y in range(0, n_img - 2 * STD_RANGE + 1, STD_STRIDE)
                   for x in range(0, n_img - 2 * STD_RANGE + 1, STD_STRIDE)]
        pool = DomainPool(P, anchors, STD_RANGE, n_img)
        e.pools, e.dom = {STD_RANGE: pool}, []
        for y in range(0, n_img, STD_RANGE):
            for x in range(0, n_img, STD_RANGE):
                d, k, si, o, _ = best_match(img[y:y + STD_RANGE, x:x + STD_RANGE].ravel(),
                                            pool, pool.candidates())
                e.maps.append((y, x, STD_RANGE, d, k, si, o))
        e.seed_bytes = 0
        e.bits = _count_bits(e, tree_bits=0)
        e.time = time.perf_counter() - t0
        return e

    # ---- proposed algorithms I and II
    import zlib
    leaves = quadtree(img, MAX_SIZE, DMIN, SPLIT_VAR)
    dom, rng_blocks, e.tau_eff = separate_domain_range(img, leaves, DMIN, tau, rule)
    e.leaves, e.dom = leaves, dom
    e.seed_mask = np.zeros(img.shape, bool)
    for (y, x, s) in dom:
        e.seed_mask[y:y + s, x:x + s] = True
    e.seed_bytes = len(zlib.compress(img[e.seed_mask].astype(np.uint8).tobytes(), 9))  # lossless part
    anchors = [(y, x) for (y, x, s) in dom]

    e.pools, r = {}, MAX_SIZE
    while r >= RMIN:
        e.pools[r] = DomainPool(P, anchors, r, n_img, use_som=(algo == "alg2"))
        r //= 2

    stack = list(rng_blocks)
    while stack:
        y, x, r = stack.pop()
        blk = img[y:y + r, x:x + r]
        pool = e.pools[r]
        lab = None
        if algo == "alg2":                                   # group label of the range block
            lab = int(pool.som.predict(block_features(blk[None]))[0])
        d, k, si, o, sse = best_match(blk.ravel(), pool, pool.candidates(lab))
        if math.sqrt(sse / (r * r)) > TOL and r > RMIN:      # poor match -> 4 smaller range blocks
            h = r // 2
            stack += [(y, x, h), (y, x + h, h), (y + h, x, h), (y + h, x + h, h)]
        else:
            e.maps.append((y, x, r, d, k, si, o))
    e.bits = _count_bits(e, tree_bits=len(leaves) * 4 // 3 + len(dom) // 8)
    e.time = time.perf_counter() - t0
    return e


def _count_bits(e, tree_bits):
    """Size of the compressed stream: IFS codes + tree + lossless seed blocks."""
    bits = tree_bits
    for (y, x, r, d, k, si, o) in e.maps:
        bits += math.ceil(math.log2(max(2, e.pools[r].n))) + ISO_BITS + S_BITS + O_BITS
        if e.algo != "standard" and r > e.rmin:
            bits += 1                                        # "split" flag
    return bits + 8 * e.seed_bytes


def compression_ratio(e):
    return e.shape[0] * e.shape[1] * 8.0 / e.bits


def decode(e, original=None, iters=DECODE_ITERS):
    """IFS decoding: iterate the maps from a flat grey image; the lossless seed blocks
    are written back at every iteration."""
    cur = np.full(e.shape, 128.0)
    use_seed = original is not None and e.seed_mask.any()
    if use_seed:
        cur[e.seed_mask] = original[e.seed_mask]
    for _ in range(iters):
        P = pool2(cur)
        new = cur.copy()
        for (y, x, r, d, k, si, o) in e.maps:
            py, px = e.pools[r].pos[d]
            new[y:y + r, x:x + r] = S_LEVELS[si] * isometry(P[py:py + 2 * r:2, px:px + 2 * r:2], k) + o
        cur = np.clip(new, 0, 255)
        if use_seed:
            cur[e.seed_mask] = original[e.seed_mask]
    return np.rint(cur)


def run(img, algo, tau=1e-5, rule=RULE, repeats=1):
    """encode + decode.  Time = mean encoding time over `repeats` runs."""
    times = []
    for _ in range(max(1, repeats)):
        e = encode(img, algo, tau, rule)
        times.append(e.time)
    rec = decode(e, img)
    return e, rec, psnr(img, rec), float(np.mean(times)), compression_ratio(e)


# ==========================================================================
# 8. Tables (same layout as the paper)
# ==========================================================================
def box(title, head, rows):
    w = [max(len(h), *(len(r[i]) for r in rows)) + 2 for i, h in enumerate(head)]
    ln = "+" + "+".join("-" * x for x in w) + "+"
    out = [title, ln, "|" + "|".join(h.center(x) for h, x in zip(head, w)) + "|", ln]
    for r in rows:
        if r[0] == "Avg":
            out.append(ln)
        out.append("|" + "|".join(c.center(x) for c, x in zip(r, w)) + "|")
    return "\n".join(out + [ln])


def md(title, head, rows):
    return (f"**{title}**\n\n| " + " | ".join(head) + " |\n|" + "---|" * len(head) + "\n" +
            "\n".join("| " + " | ".join(r) + " |" for r in rows) + "\n")


def tlabel(t):
    return "τ=10^%d" % int(round(math.log10(t)))


# ==========================================================================
# 9. Figures (the paper's Fig. 1, 2, 3, 5, 6, 7, 8)
# ==========================================================================
def make_figures(out, images, enc, t4, t4_idx):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Rectangle
    n = len(images)

    # Fig. 1: input / partitioned image / separated domain blocks (Sample images 1 and 2)
    sel = [0, min(1, n - 1)]
    fig, ax = plt.subplots(3, 2, figsize=(8, 12))
    for c, i in enumerate(sel):
        e = enc[(i, 1e-5)]
        ax[0, c].imshow(images[i], cmap="gray"); ax[0, c].set_title("Sample MRI Image %d" % (i + 1))
        ax[1, c].imshow(images[i], cmap="gray")
        for (y, x, s) in e.leaves:
            ax[1, c].add_patch(Rectangle((x, y), s, s, fill=False, ec="w", lw=0.4))
        m = np.ones(images[i].shape); m[e.seed_mask] = 0
        ax[2, c].imshow(m, cmap="gray", vmin=0, vmax=1)
    ax[0, 0].set_ylabel("Input Image"); ax[1, 0].set_ylabel("The Partitioned Image")
    ax[2, 0].set_ylabel("Separated Domain Blocks")
    for a in ax.ravel(): a.set_xticks([]); a.set_yticks([])
    fig.suptitle("Fig. 1  Feature rich and separated domain blocks")
    fig.savefig(os.path.join(out, "fig1_partition.png"), dpi=130, bbox_inches="tight"); plt.close(fig)

    # Fig. 2: domain blocks for the four thresholds (Sample images 3 and 4)
    sel = [min(2, n - 1), min(3, n - 1)]
    fig, ax = plt.subplots(len(TAU_LIST) + 1, 2, figsize=(8, 3.6 * (len(TAU_LIST) + 1)), squeeze=False)
    for c, i in enumerate(sel):
        ax[0, c].imshow(images[i], cmap="gray"); ax[0, c].set_title("Sample MRI Image %d" % (i + 1))
        for r, t in enumerate(TAU_LIST):
            m = np.ones(images[i].shape); m[enc[(i, t)].seed_mask] = 0
            ax[r + 1, c].imshow(m, cmap="gray", vmin=0, vmax=1)
            ax[r + 1, c].set_ylabel("Threshold = 1e%d" % int(round(math.log10(t))))
    for a in ax.ravel(): a.set_xticks([]); a.set_yticks([])
    fig.suptitle("Fig. 2  Domain blocks separated for various thresholds")
    fig.savefig(os.path.join(out, "fig2_thresholds.png"), dpi=110, bbox_inches="tight"); plt.close(fig)

    # Fig. 3: performance analysis (average over the images)
    avg = {k: [np.mean([enc[(i, t)].metrics[k] for i in range(n)]) for t in TAU_LIST]
           for k in ("psnr", "time", "cr")}
    xs = ["1e%d" % int(round(math.log10(t))) for t in TAU_LIST]
    fig, ax = plt.subplots(figsize=(7, 5))
    ax.plot(xs, avg["psnr"], "bd-", label="PSNR")
    ax.plot(xs, avg["time"], "ms-", label="Encoding Time")
    ax.plot(xs, avg["cr"], "b^-", mfc="none", label="Compression Ratio")
    ax.set_xlabel("The Threshold"); ax.set_ylabel("Performance"); ax.grid(True); ax.legend()
    ax.set_title("The Performance Analysis")
    fig.savefig(os.path.join(out, "fig3_performance.png"), dpi=130, bbox_inches="tight"); plt.close(fig)

    # Fig. 5: reconstructed images of Table 4
    names = ["The Std. Fractal compression Algorithm", "The Proposed Algorithm I", "The Proposed Algorithm II"]
    fig, ax = plt.subplots(1, 4, figsize=(16, 4.4))
    ax[0].imshow(images[t4_idx], cmap="gray"); ax[0].set_title("Original (Sample image %d)" % (t4_idx + 1))
    for a, k, nm in zip(ax[1:], ("standard", "alg1", "alg2"), names):
        a.imshow(t4[k][3], cmap="gray", vmin=0, vmax=255)
        a.set_title("%s\nPSNR=%.2f dB" % (nm, t4[k][0]), fontsize=9)
    for a in ax: a.axis("off")
    fig.suptitle("Fig. 5  PSNR for all three algorithms")
    fig.savefig(os.path.join(out, "fig5_reconstruction.png"), dpi=130, bbox_inches="tight"); plt.close(fig)

    # Fig. 6, 7, 8: comparison bar charts
    bn = ["Standard\nFractal Encoding", "Proposed\nAlgorithm I", "Proposed\nAlgorithm II"]
    for fn, key, yl, ttl, col in (("fig6_psnr.png", 0, "PSNR(db)", "PSNR", "#9999ff"),
                                  ("fig7_time.png", 1, "Compression Time(sec)", "Time Taken for Different Methods", "#339966"),
                                  ("fig8_cr.png", 2, "Compression Ratio", "Compression Ratio of Different Methods", "#3366ff")):
        fig, ax = plt.subplots(figsize=(5, 4))
        vals = [t4[a][key] for a in ("standard", "alg1", "alg2")]
        bars = ax.bar(bn, vals, color=col, ec="k")
        for rect, v in zip(bars, vals):
            ax.text(rect.get_x() + rect.get_width() / 2, v, "%.2f" % v, ha="center", va="bottom")
        ax.set_ylabel(yl); ax.set_title(ttl); ax.grid(axis="y")
        fig.savefig(os.path.join(out, fn), dpi=130, bbox_inches="tight"); plt.close(fig)


# ==========================================================================
# 10. Main
# ==========================================================================
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", required=True, help="archive.zip (or a folder) with the MRI images")
    ap.add_argument("--cls", default="notumor", help="class folder name (default: notumor)")
    ap.add_argument("--n", type=int, default=5, help="number of images (default 5)")
    ap.add_argument("--split", default="Training", help="use the Training/ or Testing/ part ('' = both)")
    ap.add_argument("--seed", type=int, default=1, help="seed of the (reproducible) image choice")
    ap.add_argument("--manifest", help="text file with the chosen image names; re-used if it exists")
    ap.add_argument("--size", type=int, default=IMG_SIZE, help="image side (paper: 512, multiple of 32)")
    ap.add_argument("--rule", choices=["figure", "literal"], default=RULE)
    ap.add_argument("--repeats", type=int, default=1, help="timing = mean of this many encodings")
    ap.add_argument("--t4-image", type=int, default=4, help="Sample image used in Table 4 (paper: 4)")
    ap.add_argument("--out", default="results_baseline")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)

    manifest = a.manifest or os.path.join(a.out, "selected_images.txt")
    names, items = select_images(a.source, a.cls, a.n, a.split, a.seed, manifest)
    for path in {manifest, os.path.join(a.out, "selected_images.txt")}:   # keep a copy next to the results
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(names) + "\n")
    images = [load_image(items[m](), a.size) for m in names]
    from PIL import Image
    for i, im in enumerate(images):
        Image.fromarray(im.astype(np.uint8)).save(os.path.join(a.out, "input_%d.png" % (i + 1)))
    t4_idx = min(max(a.t4_image, 1), len(images)) - 1
    mapping = ["Sample MRI Image %d = %s" % (i + 1, m) for i, m in enumerate(names)]
    settings = [
        "Settings: class=%s  images=%d  size=%dx%d  rule=%s  repeats=%d" % (a.cls, len(images), a.size, a.size, a.rule, a.repeats),
        "  quad-tree: max block %d, d_min %d, r_min %d, split variance %.0f, range RMS tolerance %.1f" % (MAX_SIZE, DMIN, RMIN, SPLIT_VAR, TOL),
        "  s: %d levels in [-0.95, 0.95]; bits: s=%d o=%d isometry=%d; seeds compressed with zlib" % (len(S_LEVELS), S_BITS, O_BITS, ISO_BITS),
        "  SOM: grid %dx%d, %d epochs, lr0 %.1f, random initial weights, linear schedules, seed %d" % (SOM_GRID[0], SOM_GRID[1], SOM_EPOCHS, SOM_LR0, SOM_SEED),
        "  tau_eff (var/var_max threshold): " + ", ".join("%s -> %.4f" % (tlabel(t), tau_effective(t, a.rule)) for t in TAU_LIST),
        "  standard coder: %dx%d ranges, 2x larger domains every %d px; decoder: %d iterations" % (STD_RANGE, STD_RANGE, STD_STRIDE, DECODE_ITERS),
        "  Table 4 image: Sample MRI Image %d" % (t4_idx + 1),
    ]
    print("\n".join(mapping + [""] + settings), flush=True)

    # ---- Tables 1-3: Algorithm II at the four thresholds
    enc = {}
    for i, im in enumerate(images):
        for t in TAU_LIST:
            e, rec, p, tm, cr = run(im, "alg2", t, a.rule, a.repeats)
            e.metrics = dict(psnr=p, time=tm, cr=cr)
            enc[(i, t)] = e
            print("  image %d  %s  PSNR=%6.2f  time=%7.2f s  CR=%6.2f  domain blocks=%d" %
                  (i + 1, tlabel(t), p, tm, cr, len(e.dom)), flush=True)
    head = ["Sample MRI Image"] + [tlabel(t) for t in TAU_LIST]
    blocks, mds = [], []
    for key, title in (("psnr", "Table 1  PSNR at Different Levels of Compression (dB)"),
                       ("time", "Table 2  Time Taken at Different Levels of Compression (sec)"),
                       ("cr", "Table 3  Compression Ratio at Different Thresholds")):
        rows = [[str(i + 1)] + ["%.2f" % enc[(i, t)].metrics[key] for t in TAU_LIST] for i in range(len(images))]
        rows.append(["Avg"] + ["%.2f" % np.mean([enc[(i, t)].metrics[key] for i in range(len(images))]) for t in TAU_LIST])
        blocks.append(box(title, head, rows)); mds.append(md(title, head, rows))

    # ---- Table 4: the three algorithms on Sample image 4, tau = 1e-5
    t4 = {}
    for algo in ("standard", "alg1", "alg2"):
        e, rec, p, tm, cr = run(images[t4_idx], algo, 1e-5, a.rule, a.repeats)
        t4[algo] = (p, tm, cr, rec)
        print("  Table 4  %-8s PSNR=%6.2f  time=%8.2f s  CR=%6.2f" % (algo, p, tm, cr), flush=True)
    h4 = ["Metric", "Standard Fractal Encoding", "Proposed Algorithm I (τ=1e-5)", "Proposed Algorithm II (τ=1e-5)"]
    r4 = [["PSNR (dB)"] + ["%.2f" % t4[k][0] for k in ("standard", "alg1", "alg2")],
          ["Compression Time (sec)"] + ["%.2f" % t4[k][1] for k in ("standard", "alg1", "alg2")],
          ["Compression Ratio"] + ["%.2f" % t4[k][2] for k in ("standard", "alg1", "alg2")]]
    ttl4 = "Table 4  PSNR achieved for Different Algorithms (Sample MRI Image %d)" % (t4_idx + 1)
    blocks.append(box(ttl4, h4, r4)); mds.append(md(ttl4, h4, r4))

    text = "\n".join(mapping) + "\n\n" + "\n".join(settings) + "\n\n" + "\n\n".join(blocks)
    print("\n" + text)
    open(os.path.join(a.out, "tables.txt"), "w", encoding="utf-8").write(text + "\n")
    open(os.path.join(a.out, "tables.md"), "w", encoding="utf-8").write(
        "```\n" + "\n".join(mapping + [""] + settings) + "\n```\n\n" + "\n".join(mds))
    make_figures(a.out, images, enc, t4, t4_idx)
    print("\nSaved in:", os.path.abspath(a.out))


if __name__ == "__main__":
    main()
